### ISSUE TITLE
Selection highlight is currently applied on partially matched word

### ISSUE THREAD

**Issue by hiiwave** [jcb91/jupyter_highlight_selected_word#11]
From #10 I've disabled the `show_token`. The only concern remained is when I select a word, it highlights all occurrence of such string disregarding whether it's a word or part of a word. i.e. when I select `rand`, it will also highlight the `rand` in `rand_number`. This behavior differs from common editors, though I'm not sure if you'd like to keep it. If the common way is preferred, I guess a workaround would be like the following (not sure yet). 
```
// main.js line 147
if (selection.length >= params.min_chars) {
    newOverlay = makeOverlay(selection, /[\w$]/, params.highlight_style);
}
```
Do you think it's reasonable, or you prefer keeping the original behavior?

**Comment by jcb91** [comment]
Right, I see what you mean, and it seems like a reasonable behaviour to adopt, at least optionally. I'll add a PR for this shortly.

**Comment by hiiwave** [comment]
Wow you did it efficiently! Yes I've tried it and it works perfectly. Great thanks for this PR! 😄

**Comment by jcb91** [comment]
Ok, I've just pushed 0.0.9 to conda-forge, it should become available as the builds finish, although the Windows 2.7 builds are still not running correctly, for reasons I don't yet understand
