### ISSUE TITLE
How can I change the highlight color?

### ISSUE THREAD

**Issue by scottdillon** [jcb91/jupyter_highlight_selected_word#2]
I'm using a dark theme. The bright green selection color contrasts badly. Can I change the selection color in the notebook.json file or would I have to download the repo, change the color in the main.js file and install from there?

I've tried to edit the color as instructed under the "Options" header in the readme but changing the color to "dim gray" or "#696969" doesn't seem to do anything. Thanks.

**Comment by scottdillon** [comment]
I had two entries on the configuration page. One with no config options but I found the other entry with the color selector option. Thanks.

**Comment by jcb91** [comment]
@scottdillon sorry for the delayed reply, just seen this issue.

> I had two entries on the configuration page

This kind of occurrence (duplicate extension listings) should hopefully be less confusing with the updated [`jupyter_nbextensions_configurator`](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) (the config extension from ipython-contrib, spun out into its own repo & with added features). I should update the readmes here to reflect that change...
