### ISSUE TITLE
Feature request: Is it possible to highlight only mouse selected text?

### ISSUE THREAD

**Issue by cibic89** [jcb91/jupyter_highlight_selected_word#24]
As it stands it highlights every time I place the cursor on a word (meeting the criteria set etc). I was after highlight only when I select the text with the mouse. I can do it using a hotkey I guess but I was after automating the process. This should reduce overhead as well.

**Comment by jcb91** [comment]
There's an option which should cover this already - the "show_token", which defines what should be highlighted when nothing is selected. See the readme, or [configurator.yaml#L74-80](https://github.com/jcb91/jupyter_highlight_selected_word/blob/e55eb467cd64b9b20ecffa2b3f18f7613f6dc65c/src/jupyter_highlight_selected_word/static/highlight_selected_word/configurator.yaml#L74-80) for details. Unless you've tried this and it's not working as it should?

**Comment by cibic89** [comment]
Hi,

Sorry about this. I read the other feature request for the answer. Closed the issue.

Thank you for the good extension!

Sent from BlueMail<http://www.bluemail.me/r?b=11626>
On 4 Jan 2018, at 13:51, Josh Barnes <notifications@github.com<mailto:notifications@github.com>> wrote:

There's an option which should cover this already - the "show_token", which defines what should be highlighted when nothing is selected. See the readme, or configurator.yaml#L74-80<https://github.com/jcb91/jupyter_highlight_selected_word/blob/e55eb467cd64b9b20ecffa2b3f18f7613f6dc65c/src/jupyter_highlight_selected_word/static/highlight_selected_word/configurator.yaml#L74-80> for details. Unless you've tried this and it's not working as it should?

**Comment by jcb91** [comment]
No worries! Thanks for kind words 😄

**Comment by Zacharias030** [comment]
This is a non-obvious setting to me, although the need is probably common. I'm glad I found the answer here.

Maybe there is a better way to expose this to the user?
