### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by myurasov** [jcb91/jupyter_highlight_selected_word#26]
I'm using Firefox 58.0.1 and JN 5.2.1 and getting the following error message in the console:

`[highlight_selected_word] error loading: DOMException("A parameter or an operation is not supported by the underlying object"). `

Highlighting does not happen. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/224567/35771653-4e27c3da-08e5-11e8-929b-072a0f240a3a.png)

**Comment by jcb91** [comment]
Apologies on the delay, I've just remembered a notification about this form last week :man_facepalming: Hmm, so this looks as though it's coming from the attempt to edit the CSS rules, although the line numbers seem inconsistent with the source here. I'll see if I can reproduce...

**Comment by jcb91** [comment]
Right, seems that Firefox objects to checks on cssRules.length before it's loaded correctly. No idea why this should be the case, but whatever, delaying seems to fix this...
