### ISSUE TITLE
zip_safe=False

### ISSUE THREAD

**Issue by jhgoebbert** [jcb91/jupyter_highlight_selected_word#29]
Hi,

you might want to add "zip_safe=False" to setup.py
to ensure, that the pyhton egg is not installed as a file, but as a directory.
(check http://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag).

Currently this gives some trouble with jupyter_contrib_nbextensions:
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1269

Best,
Jens Henrik

**Comment by jcb91** [comment]
Thanks for the report, you're right, it should be set. I think we've set this on other repos, I guess I missed it here. Will try to remember to do this in a patch release in the next few days

**Comment by jhgoebbert** [comment]
Hi Josh,

great - thanks for the quick fix.

Best,
Jens Henrik

-------------------------------------------------------------------------------------
Dipl.-Ing. Jens Henrik Goebbert
Jülich Supercomputing Centre (JSC)
Wilhelm-Johnen-Straße, 52425 Jülich, Germany
phone: +49 2461 61-96498
email: j.goebbert@fz-juelich.de<mailto:jh.goebbert@fz-juelich.de>

________________________________
