### ISSUE TITLE
possible across all notebook cells?

### ISSUE THREAD

**Issue by michaelaye** [jcb91/jupyter_highlight_selected_word#3]
Thanks for the great extension!
I was wondering though, is it possible to have the highlighting happen throughout all code cells, not only within the current one? Best if configurable, of course. ;)

**Comment by diego898** [comment]
That is what I thought it was - a kind of "Find and highlight all occurrences of a word in the notebook"

**Comment by michaelaye** [comment]
no, it works per active editor, i.e. per notebook cell.

**Comment by jcb91** [comment]
Mmm, yes, I'm sure it'd be *possible*, though it would require a rewrite of the codemirror addon `search/match-highlighter`, as it doesn't expose enough options itself. I'll have a think about it at some point

**Comment by jcb91** [comment]
Right, I've made a PR #4 which should make this work. Let me know if it solves this for you!

**Comment by michaelaye** [comment]
i have no clue how to add that PR to my current installation, sorry.

**Comment by jcb91** [comment]
@michaelaye that's ok, I've just merged it into 0.0.7 anyway, uploading to pypi shortly. Hopefully I can get it onto conda-forge too, but I've been [having issues](https://github.com/conda-forge/jupyter_contrib_nbextensions-feedstock/pull/11#issuecomment-270968393) so it may take longer...

**Comment by jcb91** [comment]
alternatively, for future reference, you can clone the repo, checkout pr #4 & install the nbextension with jupyter directly:

    git clone https://github.com/jcb91/jupyter_highlight_selected_word.git
    cd jupyter_highlight_selected_word
    git fetch origin pull/4/head:pr4
    git checkout pr4
    jupyter nbextension install --sys-prefix src/jupyter_highlight_selected_word/static/highlight_selected_word

with the relevant flags to nbextension install (since you seem to be using conda, `--sys-prefix` is probably what you want)

**Comment by jcb91** [comment]
and 0.07 is now [available from conda-forge](https://anaconda.org/conda-forge/jupyter_highlight_selected_word?version=0.0.7)
