### ISSUE TITLE
Version under conda-forge is still v0.07 (rather than current v0.08)

### ISSUE THREAD

**Issue by hiiwave** [jcb91/jupyter_highlight_selected_word#9]
Hello, 

I found this feature in v0.08 great: Prevent highlighting the currently-selected text, to make it clearer where the cursor is****

Though what I got was v0.07 as part of the jupyter_contrib_nbextensions collection.

I've also tried the following command.
```
conda install -c conda-forge jupyter_highlight_selected_word
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /anacondas/deepsim/envs/tensor3:
#
jupyter_highlight_selected_word 0.0.7                    py35_0    conda-forge
```

It seems that the version under conda is v0.07.

Could it be easily solved? Thanks.

**Comment by jcb91** [comment]
So this happens because it's a separate package installed as a dependency without an explicitly required version. I think in future it will make sense to specify versions in the requirements for the contrib repo. For now you should be able to

    conda update jupyter_highlight_selected_word

**Comment by hiiwave** [comment]
It seems that I could only get 0.07 under conda.
```
(env) $ conda update jupyter_highlight_selected_word
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /anacondas/deepsim/envs/tensor3:
#
jupyter_highlight_selected_word 0.0.7                    py35_0    conda-forge
```

**Comment by jcb91** [comment]
Oh! My apologies, it seems I got halfway through updating the co da version, and then got stuck and forgot about it (see https://github.com/conda-forge/jupyter_highlight_selected_word-feedstock/pull/4). I'm away from a computer for a few days, so it might take a little time for this, but hopefully will get to it sometime soon. Thanks for the heads up...

**Comment by hiiwave** [comment]
Thank you :)

**Comment by jcb91** [comment]
Ok, 0.0.8 is available now for osx & Linux. The [windows builds on appveyor](https://ci.appveyor.com/project/conda-forge/jupyter-highlight-selected-word-feedstock/build/1.0.8) are currently queued, so 0.0.8 windows packages should show up shortly once those builds run...

**Comment by hiiwave** [comment]
Thanks I could update to v0.08 now. Though this feature does not work to me: `Prevent highlighting the currently-selected text, to make it clearer where the cursor is`. I could verify I'm using v0.08 since the `main.css` shown in my chrome's devtool is identical to the latest version. I tried to analyze and it seems that `CodeMirror-selectedtext` isn't applied properly to selected texts under my environment. Since it's another issue, I'm closing it now.
